language: python
python:
  - "2.7"
addons:
  apt_packages:
    - libbz2-dev
    - libhdf5-serial-dev
    - liblzo2-dev
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install ."
  - "pip install coveralls"
# command to run tests
script: nosetests --with-coverage --cover-package=pysemantic
after_success:
  coveralls
